services:
  awrtc_mediasoup:
    image: awrtc_mediasoup
    ports:
      - "80:80"
      - "443:443"
      - "20000:20000/udp"
      - "20000:20000/tcp"
    logging:
        driver: "json-file"
        options:
            max-size: "100m"
            max-file: "10"
    volumes:
      - ./data/awrtc_mediasoup/config.json:/awrtc_mediasoup/config.json
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/awrtc_mediasoup/public:/awrtc_mediasoup/public
    restart: unless-stopped
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/awrtc_mediasoup/public:/var/www/certbot